GET http://localhost:3001/api/persons/

### 
// A new post with more than name and number field
POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "Tadokoro Kouji",
    "number": "114-514-1919810",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}

###
// Malformatted id
GET http://localhost:3001/api/persons/1

###
DELETE http://localhost:3001/api/persons/6a5369ecd1e036e8f520e228

### 
// Name shorter than 3 chars & wrong phone number format
POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "ET",
    "number": "1982-05-26"
}

### 
// Name shorter than 3 chars & wrong phone number format
PUT http://localhost:3001/api/persons/6967800b3cd8957d83db0ea8 HTTP/1.1
content-type: application/json

{
    "name": "Tadokoro Kouji",
    "number": "114-514-1919810"
}
