GET http://localhost:3001/api/persons/

### 
// A new post with more than name and number field
POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "Tadokoro Kouji",
    "number": "114-514-1919810",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}

###
// Malformatted id
GET http://localhost:3001/api/persons/1

### 
// Delete a record
DELETE http://localhost:3001/api/persons/6a534811e22057e7db3546c5